name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
     - name: checkout code
       uses: actions/checkout@v4
     - name: set-uo python
       uses: actions/setup-python@v5
       with:
         python-version: '3.10' 
     #- run: python my_script.py
